export const Permissions = {
  Sales: {
    View: "sales.view",
    Create: "sales.create",
    AddItems: "sales.add_items",
    Review: "sales.review",
    Cancel: "sales.cancel",
    Complete: "sales.complete",
    Void: "sales.void",
    PrintReceipt: "sales.print_receipt",
    ViewTransactions: "sales.view_transactions",
  },
  Prescriptions: {
    View: "prescriptions.view",
    Create: "prescriptions.create",
    Dispense: "prescriptions.dispense",
    Approve: "prescriptions.approve",
    ReviewControlled: "prescriptions.review_controlled",
    Override: "prescriptions.override",
  },
  Patients: {
    View: "patients.view",
    ViewBasic: "patients.view_basic",
    Create: "patients.create",
    Edit: "patients.edit",
    ViewHistory: "patients.view_history",
  },
  Inventory: {
    View: "inventory.view",
    ViewStockOnly: "inventory.view_stock_only",
    AddStock: "inventory.add_stock",
    EditStock: "inventory.edit_stock",
    AdjustStock: "inventory.adjust_stock",
    ApproveAdjustment: "inventory.approve_adjustment",
    StockCount: "inventory.stock_count",
  },
  Billing: {
    View: "billing.view",
    GenerateInvoice: "billing.generate_invoice",
    ReceivePayment: "billing.receive_payment",
    CompleteSale: "billing.complete_sale",
    PrintReceipt: "billing.print_receipt",
    Refund: "billing.refund",
    Void: "billing.void",
  },
  Reports: {
    ViewAll: "reports.view_all",
    ViewFinancial: "reports.view_financial",
    ViewOperational: "reports.view_operational",
    ViewInventory: "reports.view_inventory",
    ViewPrescription: "reports.view_prescription",
    ViewPersonalSales: "reports.view_personal_sales",
  },
  Suppliers: {
    View: "suppliers.view",
    Create: "suppliers.create",
    Edit: "suppliers.edit",
    ManageOrders: "suppliers.manage_orders",
  },
  Settings: {
    View: "settings.view",
    ManageUsers: "settings.manage_users",
    ManageRoles: "settings.manage_roles",
    ManageSystem: "settings.manage_system",
    ManageDrugCatalog: "settings.manage_drug_catalog",
  },
} as const;
