export const ROUTES = {
  LOGIN: "/login",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  DASHBOARD: "/",
  SALES: "/sales",
  CHECKOUT: "/checkout",
  PRESCRIPTIONS: "/prescriptions",
  PATIENTS: "/patients",
  INVENTORY: "/inventory",
  BILLING: "/billing",
  INSURANCE: "/insurance",
  SUPPLIERS: "/suppliers",
  REPORTS: "/reports",
  SETTINGS: "/settings",
  CHANGE_PASSWORD: "/change-password",
  PROFILE: "/profile",
} as const;
